package kz.snapar.app.ui

import kz.snapar.app.model.AppLanguage

data class UiStrings(
    val discover: String,
    val routes: String,
    val sai: String,
    val passport: String,
    val profile: String,
    val searchHint: String,
    val whereToday: String,
    val nearby: String,
    val seeAll: String,
    val trending: String,
    val interesting: String,
    val notInteresting: String,
    val saved: String,
    val whyRecommended: String,
    val about: String,
    val weather: String,
    val bestSeason: String,
    val averageCost: String,
    val calendar: String,
    val community: String,
    val askSai: String,
    val checkIn: String,
    val checkedIn: String,
    val routeBuilder: String,
    val generate: String,
    val budget: String,
    val days: String,
    val interests: String,
    val startCity: String,
    val publish: String,
    val choosePhoto: String,
    val caption: String,
    val achievements: String,
    val settings: String,
    val language: String,
    val notifications: String,
    val businessMode: String,
    val savedPlaces: String,
    val visited: String,
    val booking: String,
    val bookNow: String,
    val reviews: String,
    val gpsVerifiedBadge: String,
    val priceAnalysis: String,
    val guests: String,
    val bookingConfirmed: String,
    val bookingDemo: String,
)

fun strings(language: AppLanguage): UiStrings = when (language) {
    AppLanguage.Kazakh -> UiStrings(
        discover = "Ашу",
        routes = "Маршрут",
        sai = "SAI",
        passport = "Паспорт",
        profile = "Профиль",
        searchHint = "Көл, тау, қала немесе тур іздеу...",
        whereToday = "Бүгін қайда барамыз?",
        nearby = "Сізге жақын орындар",
        seeAll = "Барлығын көру",
        trending = "Тренд",
        interesting = "Қызықты",
        notInteresting = "Қызық емес",
        saved = "Сақталды",
        whyRecommended = "Неліктен ұсынылды?",
        about = "Бұл жер туралы",
        weather = "Ауа райы",
        bestSeason = "Үздік маусым",
        averageCost = "Орташа шығын",
        calendar = "Күнді таңдаңыз",
        community = "Қауымдастық фотолары",
        askSai = "SAI-дан маршрут сұрау",
        checkIn = "Осында болдым",
        checkedIn = "Белгіленді +250 XP",
        routeBuilder = "AI маршрут құрастыру",
        generate = "Маршрут құру",
        budget = "Бюджет",
        days = "Күн саны",
        interests = "Қызығушылық",
        startCity = "Шығу қаласы",
        publish = "Жариялау",
        choosePhoto = "Фото таңдау",
        caption = "Сипаттама",
        achievements = "Жетістіктер",
        settings = "Баптаулар",
        language = "Тіл",
        notifications = "Хабарламалар",
        businessMode = "Бизнес режим",
        savedPlaces = "Сақталған орындар",
        visited = "Барған орындар",
        booking = "Брондау",
        bookNow = "Қазір брондау",
        reviews = "Пікірлер",
        gpsVerifiedBadge = "GPS-расталған",
        priceAnalysis = "Баға талдауы",
        guests = "адам",
        bookingConfirmed = "Брондау расталды!",
        bookingDemo = "Demo · Kaspi sandbox",
    )

    AppLanguage.Russian -> UiStrings(
        discover = "Открытия",
        routes = "Маршруты",
        sai = "SAI",
        passport = "Паспорт",
        profile = "Профиль",
        searchHint = "Найти озеро, горы, город или тур...",
        whereToday = "Куда отправимся сегодня?",
        nearby = "Места рядом с вами",
        seeAll = "Смотреть все",
        trending = "В тренде",
        interesting = "Интересно",
        notInteresting = "Не моё",
        saved = "Сохранено",
        whyRecommended = "Почему рекомендовано?",
        about = "Об этом месте",
        weather = "Погода",
        bestSeason = "Лучший сезон",
        averageCost = "Средние расходы",
        calendar = "Выберите дату",
        community = "Фото сообщества",
        askSai = "Попросить маршрут у SAI",
        checkIn = "Я здесь был",
        checkedIn = "Отмечено +250 XP",
        routeBuilder = "AI-конструктор маршрута",
        generate = "Создать маршрут",
        budget = "Бюджет",
        days = "Количество дней",
        interests = "Интересы",
        startCity = "Город отправления",
        publish = "Опубликовать",
        choosePhoto = "Выбрать фото",
        caption = "Описание",
        achievements = "Достижения",
        settings = "Настройки",
        language = "Язык",
        notifications = "Уведомления",
        businessMode = "Бизнес-режим",
        savedPlaces = "Сохранённые места",
        visited = "Посещённые места",
        booking = "Бронирование",
        bookNow = "Забронировать сейчас",
        reviews = "Отзывы",
        gpsVerifiedBadge = "GPS-подтверждён",
        priceAnalysis = "Анализ цены",
        guests = "чел.",
        bookingConfirmed = "Бронь подтверждена!",
        bookingDemo = "Demo · Kaspi sandbox",
    )

    AppLanguage.English -> UiStrings(
        discover = "Discover",
        routes = "Routes",
        sai = "SAI",
        passport = "Passport",
        profile = "Profile",
        searchHint = "Search a lake, mountain, city or tour...",
        whereToday = "Where shall we go today?",
        nearby = "Places near you",
        seeAll = "See all",
        trending = "Trending",
        interesting = "Interested",
        notInteresting = "Not for me",
        saved = "Saved",
        whyRecommended = "Why was this recommended?",
        about = "About this place",
        weather = "Weather",
        bestSeason = "Best season",
        averageCost = "Average cost",
        calendar = "Choose a date",
        community = "Community photos",
        askSai = "Ask SAI for a route",
        checkIn = "I was here",
        checkedIn = "Checked in +250 XP",
        routeBuilder = "AI route builder",
        generate = "Generate route",
        budget = "Budget",
        days = "Number of days",
        interests = "Interests",
        startCity = "Starting city",
        publish = "Publish",
        choosePhoto = "Choose photo",
        caption = "Caption",
        achievements = "Achievements",
        settings = "Settings",
        language = "Language",
        notifications = "Notifications",
        businessMode = "Business mode",
        savedPlaces = "Saved places",
        visited = "Visited places",
        booking = "Booking",
        bookNow = "Book now",
        reviews = "Reviews",
        gpsVerifiedBadge = "GPS-verified",
        priceAnalysis = "Price analysis",
        guests = "guests",
        bookingConfirmed = "Booking confirmed!",
        bookingDemo = "Demo · Kaspi sandbox",
    )
}
